IF DB_ID('AllTheBeansDb') IS NULL
  CREATE DATABASE AllTheBeansDb;
GO
USE AllTheBeansDb;
GO

IF OBJECT_ID('dbo.BotdAssignments','U') IS NOT NULL DROP TABLE dbo.BotdAssignments;
IF OBJECT_ID('dbo.Orders','U') IS NOT NULL DROP TABLE dbo.Orders;
IF OBJECT_ID('dbo.Beans','U') IS NOT NULL DROP TABLE dbo.Beans;
GO

CREATE TABLE dbo.Beans(
  Id INT IDENTITY PRIMARY KEY,
  ExternalId NVARCHAR(64) NOT NULL,
  [Index] INT NOT NULL,
  IsBOTD BIT NOT NULL,
  Name NVARCHAR(100) NOT NULL,
  Colour NVARCHAR(50) NOT NULL,
  Country NVARCHAR(50) NOT NULL,
  [Description] NVARCHAR(MAX) NOT NULL,
  Image NVARCHAR(500) NOT NULL,
  Cost DECIMAL(10,2) NOT NULL
);

CREATE TABLE dbo.Orders(
  Id INT IDENTITY PRIMARY KEY,
  CustomerEmail NVARCHAR(256) NOT NULL,
  CreatedUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  BeanId INT NOT NULL FOREIGN KEY REFERENCES dbo.Beans(Id),
  Quantity INT NOT NULL,
  UnitPrice DECIMAL(10,2) NOT NULL
);

CREATE TABLE dbo.BotdAssignments(
  Id INT IDENTITY PRIMARY KEY,
  [Date] DATE NOT NULL UNIQUE,
  BeanId INT NOT NULL FOREIGN KEY REFERENCES dbo.Beans(Id)
);
